name: Publish to Crates.io

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Publish crate
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}